/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_almacen;
import clases.cl_kardex;
import clases.cl_productos_almacen;
import clases.cl_traslados;
import clases.cl_usuario;
import clases.cl_varios;
import forms.frm_reg_producto;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import sonomusic.frm_principal;

/**
 *
 * @author luis
 */
public class frm_ver_mis_productos extends javax.swing.JDialog {

    cl_productos_almacen c_mis_productos = new cl_productos_almacen();
    cl_kardex c_kardex = new cl_kardex();

    cl_varios c_varios = new cl_varios();

    int id_almacen = frm_principal.c_almacen.getId();
    int id_usuario = frm_principal.c_usuario.getId_usuario();
    int fila_seleccionada = -1;
    int kardex_seleccionado;
    int id_traslado = 0;
    String query;

    /**
     * Creates new form frm_ver_mis_productos
     */
    public frm_ver_mis_productos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        c_mis_productos.setAlmacen(id_almacen);
        cargar_tabla();
    }

    private void cargar_tabla() {
        query = "select pa.id_producto, p.descripcion, p.marca, p.modelo, p.precio, pa.cactual, p.comision, pa.f_infreso, pa.f_salida "
                + "from productos_almacen as pa "
                + "inner join productos as p on p.id_producto = pa.id_producto "
                + "where pa.id_almacen = '" + id_almacen + "' "
                + "order by p.descripcion asc , p.marca asc "
                + "limit 0";
        c_mis_productos.mis_productos(query, jTable1);
    }

    private void activar_botones() {
        btn_ajuste_kardex.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_ver_kardex.setEnabled(true);
        btn_ver_tiendas.setEnabled(true);
    }

    private void desactivar_botones() {
        btn_ajuste_kardex.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_ver_kardex.setEnabled(false);
        btn_ver_tiendas.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_kardex = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_kardex = new javax.swing.JTable();
        txt_kardex_descripcion = new javax.swing.JTextField();
        btn_detalle_kardex = new javax.swing.JButton();
        jd_ajuste_producto = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        txt_producto_kardex = new javax.swing.JTextField();
        txt_precio_kardex = new javax.swing.JTextField();
        txt_cantidad_tienda = new javax.swing.JTextField();
        txt_cantidad_kardex = new javax.swing.JTextField();
        txt_diferencia_kardex = new javax.swing.JTextField();
        jd_detalle_traslado = new javax.swing.JDialog();
        txt_tienda_origen = new javax.swing.JTextField();
        txt_tienda_destino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fecha_envio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_fecha_recepcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_usuario_envia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_id_traslado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        btn_ver_pdf_traslado = new javax.swing.JButton();
        btn_salir_traslado = new javax.swing.JButton();
        txt_usuario_recibe = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_ver_tiendas = new javax.swing.JButton();
        btn_ver_kardex = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_limpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_ajuste_kardex = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        t_kardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_kardex.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        t_kardex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_kardexMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_kardex);

        txt_kardex_descripcion.setFocusable(false);

        btn_detalle_kardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exportar.png"))); // NOI18N
        btn_detalle_kardex.setText("Ver Detalle");
        btn_detalle_kardex.setEnabled(false);
        btn_detalle_kardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detalle_kardexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_kardexLayout = new javax.swing.GroupLayout(jd_kardex.getContentPane());
        jd_kardex.getContentPane().setLayout(jd_kardexLayout);
        jd_kardexLayout.setHorizontalGroup(
            jd_kardexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_kardexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_kardexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                    .addGroup(jd_kardexLayout.createSequentialGroup()
                        .addComponent(txt_kardex_descripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_detalle_kardex)))
                .addContainerGap())
        );
        jd_kardexLayout.setVerticalGroup(
            jd_kardexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_kardexLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jd_kardexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kardex_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_detalle_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Producto:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Cantidad segun Tienda:");

        jLabel5.setText("Cantidad segun Kardex:");

        jLabel6.setText("Diferencia:");

        jToolBar2.setFloatable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
        jButton1.setText("Ajuste segun Kardex");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
        jButton2.setText("Ajuste segun Tienda");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);
        jToolBar2.add(jSeparator4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        txt_precio_kardex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_precio_kardex.setText("0.00");

        txt_cantidad_tienda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_cantidad_tienda.setText("0.00");

        txt_cantidad_kardex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_cantidad_kardex.setText("0.00");

        txt_diferencia_kardex.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_diferencia_kardex.setText("0.00");

        javax.swing.GroupLayout jd_ajuste_productoLayout = new javax.swing.GroupLayout(jd_ajuste_producto.getContentPane());
        jd_ajuste_producto.getContentPane().setLayout(jd_ajuste_productoLayout);
        jd_ajuste_productoLayout.setHorizontalGroup(
            jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ajuste_productoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ajuste_productoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_producto_kardex))
                    .addGroup(jd_ajuste_productoLayout.createSequentialGroup()
                        .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_ajuste_productoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(txt_precio_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ajuste_productoLayout.createSequentialGroup()
                                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_cantidad_tienda, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(txt_cantidad_kardex)
                                    .addComponent(txt_diferencia_kardex))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );
        jd_ajuste_productoLayout.setVerticalGroup(
            jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ajuste_productoLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_producto_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_precio_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ajuste_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diferencia_kardex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txt_tienda_origen.setEditable(false);
        txt_tienda_origen.setBackground(new java.awt.Color(255, 255, 255));

        txt_tienda_destino.setEditable(false);
        txt_tienda_destino.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Tienda Origen:");

        txt_fecha_envio.setEditable(false);
        txt_fecha_envio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Tienda Destino:");

        txt_fecha_recepcion.setEditable(false);
        txt_fecha_recepcion.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Fecha Envio:");

        txt_usuario_envia.setEditable(false);
        txt_usuario_envia.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Fecha Recepcion:");

        txt_id_traslado.setEditable(false);
        txt_id_traslado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Usuario Envia:");

        jLabel12.setText("Id. Traslado");

        jToolBar3.setFloatable(false);

        btn_ver_pdf_traslado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clipboard_text.png"))); // NOI18N
        btn_ver_pdf_traslado.setText("Ver PDf");
        btn_ver_pdf_traslado.setFocusable(false);
        btn_ver_pdf_traslado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ver_pdf_traslado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ver_pdf_traslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_pdf_trasladoActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_ver_pdf_traslado);

        btn_salir_traslado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_salir_traslado.setText("Salir");
        btn_salir_traslado.setFocusable(false);
        btn_salir_traslado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir_traslado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir_traslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_trasladoActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_salir_traslado);

        txt_usuario_recibe.setEditable(false);
        txt_usuario_recibe.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Usuario Recibe:");

        javax.swing.GroupLayout jd_detalle_trasladoLayout = new javax.swing.GroupLayout(jd_detalle_traslado.getContentPane());
        jd_detalle_traslado.getContentPane().setLayout(jd_detalle_trasladoLayout);
        jd_detalle_trasladoLayout.setHorizontalGroup(
            jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tienda_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tienda_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fecha_envio, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fecha_recepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usuario_envia, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_traslado, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usuario_recibe, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_detalle_trasladoLayout.setVerticalGroup(
            jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_detalle_trasladoLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tienda_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tienda_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha_envio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fecha_recepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario_envia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_usuario_recibe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_traslado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Mis Productos en Tienda");

        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        btn_ver_tiendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/find.png"))); // NOI18N
        btn_ver_tiendas.setText("ver en Tiendas");
        btn_ver_tiendas.setEnabled(false);
        btn_ver_tiendas.setFocusable(false);
        btn_ver_tiendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ver_tiendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ver_tiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_tiendasActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ver_tiendas);

        btn_ver_kardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clipboard_text.png"))); // NOI18N
        btn_ver_kardex.setText("ver Kardex");
        btn_ver_kardex.setEnabled(false);
        btn_ver_kardex.setFocusable(false);
        btn_ver_kardex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ver_kardex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ver_kardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_kardexActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ver_kardex);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setEnabled(false);
        btn_eliminar.setFocusable(false);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_eliminar);
        jToolBar1.add(jSeparator3);

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
        btn_limpiar.setText("Limpiar Tienda");
        btn_limpiar.setFocusable(false);
        btn_limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_limpiar);
        jToolBar1.add(jSeparator2);

        btn_ajuste_kardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
        btn_ajuste_kardex.setText("Ajustar Cantidad");
        btn_ajuste_kardex.setEnabled(false);
        btn_ajuste_kardex.setFocusable(false);
        btn_ajuste_kardex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ajuste_kardex.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ajuste_kardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajuste_kardexActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ajuste_kardex);
        jToolBar1.add(jSeparator1);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setFocusable(false);
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salir);

        jLabel1.setText("Buscar:");

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_buscar.getText().length() == 0) {
                query = "select pa.id_producto, p.descripcion, p.marca, p.modelo, p.precio, pa.cactual, p.comision, pa.f_infreso, pa.f_salida "
                        + "from productos_almacen as pa "
                        + "inner join productos as p on p.id_producto = pa.id_producto "
                        + "where pa.id_almacen = '" + id_almacen + "' "
                        + "order by p.descripcion asc , p.marca asc";
                c_mis_productos.mis_productos(query, jTable1);
            }
        }
    }//GEN-LAST:event_txt_buscarKeyPressed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        String buscar = txt_buscar.getText().trim();
        if (buscar.length() > 0) {
            query = "select pa.id_producto, p.descripcion, p.marca, p.modelo, p.precio, pa.cactual, p.comision, pa.f_infreso, pa.f_salida "
                    + "from productos_almacen as pa "
                    + "inner join productos as p on p.id_producto = pa.id_producto "
                    + "where pa.id_almacen = '" + id_almacen + "' and (p.descripcion like '%" + buscar + "%' or p.marca like '%" + buscar + "%' or p.modelo like '%" + buscar + "%' ) "
                    + "order by p.descripcion asc , p.marca asc";
            c_mis_productos.mis_productos(query, jTable1);
        }
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int contar_filas = jTable1.getRowCount();
        if (contar_filas > 0) {
            fila_seleccionada = jTable1.getSelectedRow();
            activar_botones();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_ajuste_kardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajuste_kardexActionPerformed
        if (fila_seleccionada > -1) {
            desactivar_botones();
            jd_ajuste_producto.setModal(true);
            jd_ajuste_producto.setSize(537, 297);
            jd_ajuste_producto.setLocationRelativeTo(null);

            //lenar datos dle producto
            int id_producto = Integer.parseInt(jTable1.getValueAt(fila_seleccionada, 0).toString());
            c_mis_productos.setProducto(id_producto);
            String producto = jTable1.getValueAt(fila_seleccionada, 1).toString() + " " + jTable1.getValueAt(fila_seleccionada, 2).toString();
            double precio = Double.parseDouble(jTable1.getValueAt(fila_seleccionada, 4).toString());
            double cantidad = Double.parseDouble(jTable1.getValueAt(fila_seleccionada, 3).toString());
            txt_producto_kardex.setText(producto);
            txt_precio_kardex.setText(c_varios.formato_totales(precio));
            txt_cantidad_tienda.setText(c_varios.formato_totales(cantidad));
            c_kardex.setId_producto(id_producto);
            c_kardex.setId_almacen(id_almacen);
            double stock = c_kardex.obtener_suma_kardex();
            txt_cantidad_kardex.setText(c_varios.formato_totales(stock));
            txt_diferencia_kardex.setText(c_varios.formato_totales(stock - cantidad) + "");

            //,mostrar modal
            jd_ajuste_producto.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO HA SELECCIONADO UNA FILA");
        }
    }//GEN-LAST:event_btn_ajuste_kardexActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(null, "¿Esta Seguro de Limpiar los productos de esta tienda?");

        if (JOptionPane.OK_OPTION == confirmado) {
            c_mis_productos.setAlmacen(id_almacen);
            c_mis_productos.limpiar_tienda();

            query = "select pa.id_producto, p.descripcion, p.marca, p.modelo, p.precio, pa.cactual, p.comision, pa.f_infreso, pa.f_salida "
                    + "from productos_almacen as pa "
                    + "inner join productos as p on p.id_producto = pa.id_producto "
                    + "where pa.id_almacen = '" + id_almacen + "' "
                    + "order by p.descripcion asc , p.marca asc ";
            c_mis_productos.mis_productos(query, jTable1);
        }
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_ver_kardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_kardexActionPerformed
        if (fila_seleccionada > -1) {
            desactivar_botones();
            jd_kardex.setModal(true);
            jd_kardex.setSize(840, 480);
            jd_kardex.setLocationRelativeTo(null);
            int id_producto = Integer.parseInt(jTable1.getValueAt(fila_seleccionada, 0).toString());
            String producto = jTable1.getValueAt(fila_seleccionada, 1).toString() + " " + jTable1.getValueAt(fila_seleccionada, 2).toString();
            txt_kardex_descripcion.setText(producto);
            c_kardex.setId_producto(id_producto);
            c_kardex.setId_almacen(id_almacen);
            c_kardex.ver_kardex(t_kardex);
            jd_kardex.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "NO HA SELECCIONADO UNA FILA");
        }
    }//GEN-LAST:event_btn_ver_kardexActionPerformed

    private void btn_ver_tiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_tiendasActionPerformed
        if (fila_seleccionada > -1) {
            desactivar_botones();
            int id_producto = Integer.parseInt(jTable1.getValueAt(fila_seleccionada, 0).toString());
            Frame f = JOptionPane.getRootFrame();
            frm_ver_ubicacion_producto.id_producto = id_producto;
            frm_ver_ubicacion_producto dialog = new frm_ver_ubicacion_producto(f, true);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btn_ver_tiendasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jd_ajuste_producto.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ajuste segun kardex 
        //cambiar cantidad actual por cantidad segun kardex
        //update productos_almacen set cantidad = _stock
        c_mis_productos.setCantidad(c_kardex.obtener_suma_kardex());
        if (c_mis_productos.actualizar_cantidad_producto()) {
            jd_ajuste_producto.dispose();
            c_mis_productos.mis_productos(query, jTable1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double cantidad = Double.parseDouble(jTable1.getValueAt(fila_seleccionada, 3).toString());
        double precio = Double.parseDouble(jTable1.getValueAt(fila_seleccionada, 4).toString());
        int stock = this.c_kardex.obtener_suma_kardex();

        c_kardex.obtener_codigo();
        c_kardex.setFecha(c_varios.getFechaActual());
        c_kardex.setId_tido(9);
        c_kardex.setId_tipo_movimiento(14);
        c_kardex.setSerie(c_varios.obtener_anio() + "");
        c_kardex.setNumero(c_kardex.getId_kardex());
        c_kardex.setId_usuario(id_usuario);
        //ajuste segun tienda 
        //si diferencia es mayor 
        if (cantidad > stock) {
            c_kardex.setCant_salida(0);
            c_kardex.setCant_ingreso(cantidad - stock);
            c_kardex.setCosto_salida(0);
            c_kardex.setCosto_ingreso(precio);
        }

        if (stock > cantidad) {
            c_kardex.setCant_salida(stock - cantidad);
            c_kardex.setCant_ingreso(0);
            c_kardex.setCosto_salida(precio);
            c_kardex.setCosto_ingreso(0);
        }

        if (c_kardex.regitrar()) {
            jd_ajuste_producto.dispose();
            c_mis_productos.mis_productos(query, jTable1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_kardexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_kardexMouseClicked
        kardex_seleccionado = t_kardex.getSelectedRow();
        btn_detalle_kardex.setEnabled(true);
    }//GEN-LAST:event_t_kardexMouseClicked

    private void btn_detalle_kardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detalle_kardexActionPerformed
        if (kardex_seleccionado > -1) {
            btn_detalle_kardex.setEnabled(false);
            
            int idkardex = Integer.parseInt(t_kardex.getValueAt(kardex_seleccionado, 0).toString());
            cl_kardex c_kardexdetalle = new cl_kardex();
            c_kardexdetalle.setId_kardex(idkardex);
            c_kardexdetalle.setId_almacen(id_almacen);
            c_kardexdetalle.setId_producto(c_kardex.getId_producto());
            c_kardexdetalle.obtener_datos();

            if (c_kardexdetalle.getId_tipo_movimiento() == 11) {
                cl_traslados c_traslado = new cl_traslados();
                c_traslado.setId_traslado(c_kardexdetalle.getNumero());
                c_traslado.validar_datos();
                
                id_traslado = c_traslado.getId_traslado();

                cl_almacen c_tenvia = new cl_almacen();
                c_tenvia.setId(c_traslado.getId_tienda_envia());
                c_tenvia.validar_almacen();

                cl_almacen c_trecibe = new cl_almacen();
                c_trecibe.setId(c_traslado.getId_tienda_recibe());
                c_trecibe.validar_almacen();
                
                cl_usuario c_uenvia = new cl_usuario();
                c_uenvia.setId_usuario(c_traslado.getId_usuario_envia());
                c_uenvia.validar_usuario();
                
                
                cl_usuario c_urecibe = new cl_usuario();
                c_urecibe.setId_usuario(c_traslado.getId_usuario_recibe());
                c_urecibe.validar_usuario();
                
                txt_tienda_origen.setText(c_tenvia.getNombre());
                txt_tienda_destino.setText(c_trecibe.getNombre());
                txt_fecha_envio.setText(c_traslado.getFecha_envio());
                txt_fecha_recepcion.setText(c_traslado.getFecha_recepcion());
                txt_usuario_envia.setText(c_uenvia.getNombre());
                txt_usuario_recibe.setText(c_urecibe.getNombre());
                txt_id_traslado.setText(c_traslado.getId_traslado()+"");
                

                jd_detalle_traslado.setModal(true);
                jd_detalle_traslado.setSize(516, 382);
                jd_detalle_traslado.setLocationRelativeTo(null);
                jd_detalle_traslado.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_detalle_kardexActionPerformed

    private void btn_salir_trasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_trasladoActionPerformed
        jd_detalle_traslado.dispose();
    }//GEN-LAST:event_btn_salir_trasladoActionPerformed

    private void btn_ver_pdf_trasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_pdf_trasladoActionPerformed
         // TODO add your handling code here:
        File miDir = new File(".");
        try {
            Map<String, Object> parametros = new HashMap<>();
        String path = miDir.getCanonicalPath();
         String direccion = path + "//reports//subreports//"; 
         System.out.println(direccion); 
         parametros.put("SUBREPORT_DIR", direccion); 
         parametros.put("JRParameter.REPORT_LOCALE", Locale.ENGLISH); 
         parametros.put("id_traslado", id_traslado); 
         //c_varios.imp_reporte("rpt_documento_venta", parametros);
               c_varios.ver_reporte("report_traslado", parametros); 
       
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage()); 
        }
    }//GEN-LAST:event_btn_ver_pdf_trasladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ver_mis_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ver_mis_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ver_mis_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ver_mis_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_ver_mis_productos dialog = new frm_ver_mis_productos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ajuste_kardex;
    private javax.swing.JButton btn_detalle_kardex;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salir_traslado;
    private javax.swing.JButton btn_ver_kardex;
    private javax.swing.JButton btn_ver_pdf_traslado;
    private javax.swing.JButton btn_ver_tiendas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JDialog jd_ajuste_producto;
    private javax.swing.JDialog jd_detalle_traslado;
    private javax.swing.JDialog jd_kardex;
    private javax.swing.JTable t_kardex;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidad_kardex;
    private javax.swing.JTextField txt_cantidad_tienda;
    private javax.swing.JTextField txt_diferencia_kardex;
    private javax.swing.JTextField txt_fecha_envio;
    private javax.swing.JTextField txt_fecha_recepcion;
    private javax.swing.JTextField txt_id_traslado;
    private javax.swing.JTextField txt_kardex_descripcion;
    private javax.swing.JTextField txt_precio_kardex;
    private javax.swing.JTextField txt_producto_kardex;
    private javax.swing.JTextField txt_tienda_destino;
    private javax.swing.JTextField txt_tienda_origen;
    private javax.swing.JTextField txt_usuario_envia;
    private javax.swing.JTextField txt_usuario_recibe;
    // End of variables declaration//GEN-END:variables
}
