/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_almacen;
import clases.cl_documentos_almacen;
import clases.cl_empresa;
import clases_autocomplete.cla_empresa;
import clases_autocomplete.cla_mis_documentos;
import java.awt.event.KeyEvent;
import models.m_documentos_sunat;
import models.m_empresas;

/**
 *
 * @author CALIDAD
 */
public class frm_ver_almacenes extends javax.swing.JInternalFrame {

    cl_almacen c_almacen = new cl_almacen();
    cl_empresa c_empresa = new cl_empresa();

    cl_documentos_almacen c_mis_documentos = new cl_documentos_almacen();

    int fila_seleccionada;

    /**
     * Creates new form frm_ver_almacenes
     */
    public frm_ver_almacenes() {
        initComponents();
        mostrar_tabla();

        //cargar documentos sunat en combobox
        m_documentos_sunat m_documentos = new m_documentos_sunat();
        m_documentos.cbx_documentos(cbx_doc_sunat);
    }

    private void mostrar_tabla() {
        String query = "select a.id_almacen, a.nombre, a.direccion, a.ciudad, a.estado, e.ruc, e.razon "
                + "from almacen as a "
                + "inner join empresa as e on e.id_empresa = a.id_empresa "
                + "order by a.nombre asc";
        c_almacen.mostrar(t_tiendas, query);
    }

    private void activar_campos() {
        txt_j_nombre.setEnabled(true);
        txt_j_direccion.setEnabled(true);
        txt_j_ciudad.setEnabled(true);
        txt_j_ticketera.setEnabled(true);
        cbx_j_empresa.requestFocus();
    }

    private void reiniciar_campos() {
        txt_j_nombre.setEnabled(false);
        txt_j_direccion.setEnabled(false);
        txt_j_ciudad.setEnabled(false);
        txt_j_ticketera.setEnabled(false);
        txt_j_nombre.setText("");
        txt_j_direccion.setText("");
        txt_j_ciudad.setText("");
        txt_j_ticketera.setText("");
        cbx_j_empresa.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_reg_tienda = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_j_id = new javax.swing.JTextField();
        txt_j_nombre = new javax.swing.JTextField();
        txt_j_direccion = new javax.swing.JTextField();
        txt_j_ciudad = new javax.swing.JTextField();
        txt_j_ticketera = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbx_j_empresa = new javax.swing.JComboBox<>();
        jToolBar2 = new javax.swing.JToolBar();
        btn_j_grabar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_j_cancelar = new javax.swing.JButton();
        txt_j_ubigeo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_j_telefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jd_ver_doc_sunat = new javax.swing.JDialog();
        jToolBar3 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_documentos = new javax.swing.JTable();
        jd_reg_doc_sunat = new javax.swing.JDialog();
        jToolBar4 = new javax.swing.JToolBar();
        btn_reg_documento = new javax.swing.JButton();
        btn_salir_documento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_doc_sunat = new javax.swing.JComboBox<>();
        txt_serie = new javax.swing.JTextField();
        txt_numero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_tiendas = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_doc_sunat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_cerrar = new javax.swing.JButton();

        jd_reg_tienda.setTitle("Registrar Tienda");

        jLabel1.setText("Id.:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Direccion:");

        jLabel4.setText("Ciudad:");

        jLabel5.setText("Ticketera:");

        txt_j_id.setEnabled(false);

        txt_j_nombre.setEnabled(false);
        txt_j_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_j_nombreKeyPressed(evt);
            }
        });

        txt_j_direccion.setEnabled(false);
        txt_j_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_j_direccionKeyPressed(evt);
            }
        });

        txt_j_ciudad.setEnabled(false);
        txt_j_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_j_ciudadKeyPressed(evt);
            }
        });

        txt_j_ticketera.setEnabled(false);
        txt_j_ticketera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_j_ticketeraKeyPressed(evt);
            }
        });

        jLabel6.setText("Empresa:");

        cbx_j_empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10469932091 | OYANGUREN GIRON LUIS ENRIQUE", "10718449559 | DE LA CRUZ ESPINOZA ANDREA TATIANA" }));
        cbx_j_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_j_empresaKeyPressed(evt);
            }
        });

        jToolBar2.setFloatable(false);
        jToolBar2.setOpaque(false);

        btn_j_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btn_j_grabar.setText("Grabar");
        btn_j_grabar.setEnabled(false);
        btn_j_grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_j_grabar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_j_grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_j_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_j_grabarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_j_grabar);
        jToolBar2.add(jSeparator2);

        btn_j_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_j_cancelar.setText("Cancelar");
        btn_j_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_j_cancelar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_j_cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_j_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_j_cancelarActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_j_cancelar);

        txt_j_ubigeo.setEnabled(false);
        txt_j_ubigeo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_j_ubigeoKeyPressed(evt);
            }
        });

        jLabel10.setText("Ubigeo:");

        txt_j_telefono.setEnabled(false);
        txt_j_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_j_telefonoKeyPressed(evt);
            }
        });

        jLabel11.setText("Telefono:");

        javax.swing.GroupLayout jd_reg_tiendaLayout = new javax.swing.GroupLayout(jd_reg_tienda.getContentPane());
        jd_reg_tienda.getContentPane().setLayout(jd_reg_tiendaLayout);
        jd_reg_tiendaLayout.setHorizontalGroup(
            jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_j_direccion))
                    .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                        .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                                .addComponent(txt_j_id, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbx_j_empresa, 0, 499, Short.MAX_VALUE)))
                    .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                        .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_j_telefono))
                            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_j_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_j_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_j_ticketera))
                            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_j_ubigeo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_reg_tiendaLayout.setVerticalGroup(
            jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_tiendaLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_j_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_ticketera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_ubigeo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_tiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_j_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_ver_doc_sunat.setTitle("Ver Documentos de esta Tienda");

        jToolBar3.setFloatable(false);
        jToolBar3.setEnabled(false);
        jToolBar3.setOpaque(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_add.png"))); // NOI18N
        jButton1.setText("Agregar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        jButton2.setText("Modificar");
        jButton2.setEnabled(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.setEnabled(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton4);

        t_documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_documentos);

        javax.swing.GroupLayout jd_ver_doc_sunatLayout = new javax.swing.GroupLayout(jd_ver_doc_sunat.getContentPane());
        jd_ver_doc_sunat.getContentPane().setLayout(jd_ver_doc_sunatLayout);
        jd_ver_doc_sunatLayout.setHorizontalGroup(
            jd_ver_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jd_ver_doc_sunatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_ver_doc_sunatLayout.setVerticalGroup(
            jd_ver_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ver_doc_sunatLayout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar4.setFloatable(false);
        jToolBar4.setEnabled(false);
        jToolBar4.setOpaque(false);

        btn_reg_documento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_add.png"))); // NOI18N
        btn_reg_documento.setText("Agregar");
        btn_reg_documento.setFocusable(false);
        btn_reg_documento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reg_documento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_reg_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reg_documentoActionPerformed(evt);
            }
        });
        jToolBar4.add(btn_reg_documento);

        btn_salir_documento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btn_salir_documento.setText("Salir");
        btn_salir_documento.setFocusable(false);
        btn_salir_documento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir_documento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salir_documentoActionPerformed(evt);
            }
        });
        jToolBar4.add(btn_salir_documento);

        jLabel7.setText("Documento Sunat:");

        jLabel8.setText("Serie:");

        jLabel9.setText("Numero:");

        cbx_doc_sunat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOLETA", "FACTURA", "NOTA DE VENTA", "ETC.", "ETC" }));

        txt_serie.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jd_reg_doc_sunatLayout = new javax.swing.GroupLayout(jd_reg_doc_sunat.getContentPane());
        jd_reg_doc_sunat.getContentPane().setLayout(jd_reg_doc_sunatLayout);
        jd_reg_doc_sunatLayout.setHorizontalGroup(
            jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jd_reg_doc_sunatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(46, 46, 46)
                .addGroup(jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbx_doc_sunat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_serie)
                    .addComponent(txt_numero))
                .addContainerGap())
        );
        jd_reg_doc_sunatLayout.setVerticalGroup(
            jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_reg_doc_sunatLayout.createSequentialGroup()
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_doc_sunat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_reg_doc_sunatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setTitle("Ver Tiendas");

        t_tiendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_tiendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_tiendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_tiendas);

        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_agregar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_agregar);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_modificar);

        btn_doc_sunat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        btn_doc_sunat.setText("Doc. Sunat");
        btn_doc_sunat.setEnabled(false);
        btn_doc_sunat.setFocusable(false);
        btn_doc_sunat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doc_sunat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doc_sunat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doc_sunatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_doc_sunat);
        jToolBar1.add(jSeparator1);

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_cerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_cerrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        jd_reg_tienda.setModal(true);
        jd_reg_tienda.setSize(621, 334);
        jd_reg_tienda.setLocationRelativeTo(null);
        reiniciar_campos();
        m_empresas m_empresas = new m_empresas();
        m_empresas.cbx_empresas(cbx_j_empresa);
        cbx_j_empresa.requestFocus();
        jd_reg_tienda.setVisible(true);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_j_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_j_cancelarActionPerformed
        jd_reg_tienda.dispose();
    }//GEN-LAST:event_btn_j_cancelarActionPerformed

    private void cbx_j_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_j_empresaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_j_nombre.setEnabled(true);
            txt_j_nombre.requestFocus();
        }
    }//GEN-LAST:event_cbx_j_empresaKeyPressed

    private void txt_j_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_j_nombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String nnombre = txt_j_nombre.getText().trim();
            if (nnombre.length() > 0) {
                txt_j_direccion.setEnabled(true);
                txt_j_direccion.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_j_nombreKeyPressed

    private void txt_j_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_j_direccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String ntexto = txt_j_direccion.getText().trim();
            if (ntexto.length() > 0) {
                txt_j_ciudad.setEnabled(true);
                txt_j_ciudad.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_j_direccionKeyPressed

    private void txt_j_ciudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_j_ciudadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String ntexto = txt_j_ciudad.getText().trim();
            if (ntexto.length() > 0) {
                txt_j_ticketera.setEnabled(true);
                txt_j_ticketera.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_j_ciudadKeyPressed

    private void txt_j_ticketeraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_j_ticketeraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String ntexto = txt_j_ticketera.getText().trim();
            if (ntexto.length() >= 0) {
                txt_j_ubigeo.setEnabled(true);
                txt_j_ubigeo.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_j_ticketeraKeyPressed

    private void btn_j_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_j_grabarActionPerformed
        cla_empresa o_empresa = (cla_empresa) cbx_j_empresa.getSelectedItem();
        c_almacen.setEmpresa(o_empresa.getId_empresa());
        c_almacen.setNombre(txt_j_nombre.getText());
        c_almacen.setDireccion(txt_j_direccion.getText());
        c_almacen.setCiudad(txt_j_ciudad.getText());
        c_almacen.setTicketera(txt_j_ticketera.getText());

        if (c_almacen.getId() == 0) {
            c_almacen.obtener_codigo();
            c_almacen.registrar();
        } else {
            c_almacen.modificar();
        }

        mostrar_tabla();
        jd_reg_tienda.dispose();
    }//GEN-LAST:event_btn_j_grabarActionPerformed

    private void t_tiendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_tiendasMouseClicked
        if (evt.getClickCount() == 2) {
            fila_seleccionada = t_tiendas.getSelectedRow();
            c_almacen.setId(Integer.parseInt(t_tiendas.getValueAt(fila_seleccionada, 0).toString()));
            btn_modificar.setEnabled(true);
            btn_doc_sunat.setEnabled(true);
        }
    }//GEN-LAST:event_t_tiendasMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        jd_reg_tienda.setModal(true);
        jd_reg_tienda.setSize(621, 334);
        jd_reg_tienda.setLocationRelativeTo(null);

        btn_modificar.setEnabled(false);
        activar_campos();
        m_empresas m_empresas = new m_empresas();
        m_empresas.cbx_empresas(cbx_j_empresa);

        c_almacen.validar_almacen();
        txt_j_id.setText(c_almacen.getId() + "");
        txt_j_nombre.setText(c_almacen.getNombre());
        txt_j_direccion.setText(c_almacen.getDireccion());
        txt_j_ciudad.setText(c_almacen.getCiudad());
        txt_j_ticketera.setText(c_almacen.getTicketera());
        txt_j_ubigeo.setText(c_almacen.getUbigeo());
        txt_j_telefono.setText(c_almacen.getTelefono());
        c_empresa.setId(c_almacen.getEmpresa());
        c_empresa.validar_empresa();
        cbx_j_empresa.getModel().setSelectedItem(new cla_empresa(c_empresa.getId(), c_empresa.getRuc(), c_empresa.getRazon()));

        jd_reg_tienda.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void llamar_ver_documentos() {
        jd_ver_doc_sunat.setModal(true);
        jd_ver_doc_sunat.setSize(400, 350);
        jd_ver_doc_sunat.setLocationRelativeTo(null);
        String query = "select da.id_tido, ds.descripcion, da.serie, da.numero "
                + "from documentos_almacen as da "
                + "inner join documentos_sunat as ds on ds.id_tido= da.id_tido "
                + "where da.id_almacen = '" + c_almacen.getId() + "' "
                + "order by ds.descripcion asc";
        c_mis_documentos.mostrar(t_documentos, query);
        jd_ver_doc_sunat.setVisible(true);
    }

    private void btn_doc_sunatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doc_sunatActionPerformed
        btn_doc_sunat.setEnabled(false);
        btn_modificar.setEnabled(false);
        llamar_ver_documentos();
    }//GEN-LAST:event_btn_doc_sunatActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jd_ver_doc_sunat.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_salir_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salir_documentoActionPerformed
        jd_reg_doc_sunat.dispose();
        llamar_ver_documentos();
    }//GEN-LAST:event_btn_salir_documentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_ver_doc_sunat.dispose();
        jd_reg_doc_sunat.setModal(true);
        jd_reg_doc_sunat.setSize(400, 350);
        jd_reg_doc_sunat.setLocationRelativeTo(null);
        jd_reg_doc_sunat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_reg_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reg_documentoActionPerformed
        c_mis_documentos.setSerie(txt_serie.getText());
        c_mis_documentos.setNumero(Integer.parseInt(txt_numero.getText()));
        cla_mis_documentos m_seleccionado = (cla_mis_documentos) cbx_doc_sunat.getSelectedItem();
        c_mis_documentos.setId_tido(m_seleccionado.getId_tido());
        c_mis_documentos.setId_almacen(c_almacen.getId());

        if (c_mis_documentos.registrar()) {
            jd_reg_doc_sunat.dispose();
            llamar_ver_documentos();
        }
    }//GEN-LAST:event_btn_reg_documentoActionPerformed

    private void txt_j_ubigeoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_j_ubigeoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String ntexto = txt_j_ubigeo.getText().trim();
            if (ntexto.length() == 6) {
                txt_j_telefono.setEnabled(true);
                txt_j_telefono.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_j_ubigeoKeyPressed

    private void txt_j_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_j_telefonoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String ntexto = txt_j_telefono.getText().trim();
            if (ntexto.length() == 9) {
                btn_j_grabar.setEnabled(true);
                btn_j_grabar.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_j_telefonoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_doc_sunat;
    private javax.swing.JButton btn_j_cancelar;
    private javax.swing.JButton btn_j_grabar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_reg_documento;
    private javax.swing.JButton btn_salir_documento;
    private javax.swing.JComboBox<String> cbx_doc_sunat;
    private javax.swing.JComboBox<String> cbx_j_empresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JDialog jd_reg_doc_sunat;
    private javax.swing.JDialog jd_reg_tienda;
    private javax.swing.JDialog jd_ver_doc_sunat;
    private javax.swing.JTable t_documentos;
    private javax.swing.JTable t_tiendas;
    private javax.swing.JTextField txt_j_ciudad;
    private javax.swing.JTextField txt_j_direccion;
    private javax.swing.JTextField txt_j_id;
    private javax.swing.JTextField txt_j_nombre;
    private javax.swing.JTextField txt_j_telefono;
    private javax.swing.JTextField txt_j_ticketera;
    private javax.swing.JTextField txt_j_ubigeo;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextField txt_serie;
    // End of variables declaration//GEN-END:variables
}
